const sampleListings = [
  {
    title: "Cozy Apartment in New York",
    description: "A beautiful and cozy 2-bedroom apartment in the heart of Manhattan.",
    image: "https://images.unsplash.com/photo-1560185127-6ed189bf02a7?w=900&auto=format&fit=crop&q=60",
    price: 2500,
    location: "Manhattan, New York",
    country: "USA",
  },
  {
    title: "Beachside Villa in Goa",
    description: "Luxury villa with ocean view, private pool, and modern amenities.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&auto=format&fit=crop&q=60",
    price: 18000,
    location: "Candolim, Goa",
    country: "India",
  },
  {
    title: "Modern Loft in London",
    description: "Spacious loft with contemporary interiors near Tower Bridge.",
    image: "https://images.unsplash.com/photo-1598928506311-c55ded5d4c9d?w=900&auto=format&fit=crop&q=60",
    price: 3200,
    location: "Tower Bridge, London",
    country: "UK",
  },
  {
    title: "Traditional House in Kyoto",
    description: "Experience Japanese culture in a traditional machiya house.",
    image: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=900&auto=format&fit=crop&q=60",
    price: 120,
    location: "Gion, Kyoto",
    country: "Japan",
  },
  {
    title: "Mountain Cabin in Switzerland",
    description: "Cozy wooden cabin with fireplace and stunning Alps view.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=900&auto=format&fit=crop&q=60",
    price: 400,
    location: "Interlaken",
    country: "Switzerland",
  },
  {
    title: "Desert Camp in Dubai",
    description: "Luxury desert camping experience with camel rides and starry nights.",
    image: "https://images.unsplash.com/photo-1573496529574-be85d6a60704?w=900&auto=format&fit=crop&q=60",
    price: 600,
    location: "Dubai Desert",
    country: "UAE",
  },
  {
    title: "Countryside Farmhouse in Tuscany",
    description: "Rustic farmhouse surrounded by vineyards and olive groves.",
    image: "https://images.unsplash.com/photo-1505691723518-36a1b1a4d12e?w=900&auto=format&fit=crop&q=60",
    price: 200,
    location: "Tuscany",
    country: "Italy",
  },
  {
    title: "Lakefront Cottage in Canada",
    description: "Peaceful cottage with direct access to lake and kayaking facilities.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&auto=format&fit=crop&q=60",
    price: 150,
    location: "Ontario",
    country: "Canada",
  },
  {
    title: "Skyline Penthouse in Singapore",
    description: "Luxurious penthouse with panoramic city views and infinity pool.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&auto=format&fit=crop&q=60",
    price: 9500,
    location: "Marina Bay",
    country: "Singapore",
  },
  {
    title: "Ski Chalet in Austria",
    description: "Warm and cozy chalet perfect for skiing enthusiasts.",
    image: "https://images.unsplash.com/photo-1505691723518-36a1b1a4d12e?w=900&auto=format&fit=crop&q=60",
    price: 350,
    location: "Innsbruck",
    country: "Austria",
  },
  {
    title: "Safari Lodge in Kenya",
    description: "Eco-lodge offering close encounters with wildlife.",
    image: "https://images.unsplash.com/photo-1573496529574-be85d6a60704?w=900&auto=format&fit=crop&q=60",
    price: 500,
    location: "Maasai Mara",
    country: "Kenya",
  },
  {
    title: "Island Bungalow in Maldives",
    description: "Overwater bungalow with crystal clear lagoon views.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=900&auto=format&fit=crop&q=60",
    price: 1200,
    location: "Male Atoll",
    country: "Maldives",
  },
  {
    title: "Historic Apartment in Paris",
    description: "Elegant apartment near the Eiffel Tower.",
    image: "https://images.unsplash.com/photo-1560185127-6ed189bf02a7?w=900&auto=format&fit=crop&q=60",
    price: 2700,
    location: "Paris",
    country: "France",
  },
  {
    title: "Jungle Retreat in Bali",
    description: "Private villa surrounded by lush rainforest.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&auto=format&fit=crop&q=60",
    price: 300,
    location: "Ubud",
    country: "Indonesia",
  },
  {
    title: "City Studio in Berlin",
    description: "Modern studio apartment close to nightlife.",
    image: "https://images.unsplash.com/photo-1505691723518-36a1b1a4d12e?w=900&auto=format&fit=crop&q=60",
    price: 800,
    location: "Berlin",
    country: "Germany",
  },
  {
    title: "Cliffside House in Santorini",
    description: "Traditional whitewashed home with sea views.",
    image: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=900&auto=format&fit=crop&q=60",
    price: 500,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Urban Flat in Dubai",
    description: "Stylish city apartment with luxury amenities.",
    image: "https://images.unsplash.com/photo-1598928506311-c55ded5d4c9d?w=900&auto=format&fit=crop&q=60",
    price: 1500,
    location: "Downtown Dubai",
    country: "UAE",
  },
  {
    title: "Seaside Cottage in Ireland",
    description: "Quaint stone cottage overlooking the Atlantic.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&auto=format&fit=crop&q=60",
    price: 180,
    location: "Galway",
    country: "Ireland",
  },
  {
    title: "Luxury Condo in Hong Kong",
    description: "High-rise condo with skyline views.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=900&auto=format&fit=crop&q=60",
    price: 4200,
    location: "Central Hong Kong",
    country: "China",
  },
  {
    title: "Wine Estate Stay in Napa Valley",
    description: "Rustic villa surrounded by vineyards.",
    image: "https://images.unsplash.com/photo-1505691723518-36a1b1a4d12e?w=900&auto=format&fit=crop&q=60",
    price: 600,
    location: "Napa Valley",
    country: "USA",
  },
  {
    title: "Treehouse in Costa Rica",
    description: "Eco-friendly treehouse surrounded by jungle.",
    image: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=900&auto=format&fit=crop&q=60",
    price: 120,
    location: "Monteverde",
    country: "Costa Rica",
  },
  {
    title: "Igloo Stay in Finland",
    description: "Glass igloo perfect for viewing the Northern Lights.",
    image: "https://images.unsplash.com/photo-1560185127-6ed189bf02a7?w=900&auto=format&fit=crop&q=60",
    price: 700,
    location: "Lapland",
    country: "Finland",
  },
  {
    title: "Castle Room in Scotland",
    description: "Stay like royalty in a historic castle.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&auto=format&fit=crop&q=60",
    price: 450,
    location: "Edinburgh",
    country: "Scotland",
  },
  {
    title: "Surf Shack in Hawaii",
    description: "Beach hut ideal for surfers and ocean lovers.",
    image: "https://images.unsplash.com/photo-1505691723518-36a1b1a4d12e?w=900&auto=format&fit=crop&q=60",
    price: 250,
    location: "Maui",
    country: "USA",
  },
  {
    title: "Desert Dome in Arizona",
    description: "Unique dome stay with desert landscapes.",
    image: "https://images.unsplash.com/photo-1573496529574-be85d6a60704?w=900&auto=format&fit=crop&q=60",
    price: 140,
    location: "Phoenix",
    country: "USA",
  },
  {
    title: "Luxury Houseboat in Kerala",
    description: "Traditional houseboat with modern luxuries.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=900&auto=format&fit=crop&q=60",
    price: 220,
    location: "Alleppey",
    country: "India",
  },
  {
    title: "Historic Riad in Morocco",
    description: "Traditional Moroccan riad with courtyard.",
    image: "https://images.unsplash.com/photo-1505691723518-36a1b1a4d12e?w=900&auto=format&fit=crop&q=60",
    price: 170,
    location: "Marrakech",
    country: "Morocco",
  },
  {
    title: "Cave House in Cappadocia",
    description: "Unique cave dwelling with stone interiors.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&auto=format&fit=crop&q=60",
    price: 300,
    location: "Göreme",
    country: "Turkey",
  },
  {
    title: "Desert Tent in Rajasthan",
    description: "Luxury tented camp in the Thar desert.",
    image: "https://images.unsplash.com/photo-1560185127-6ed189bf02a7?w=900&auto=format&fit=crop&q=60",
    price: 110,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Countryside Inn in Poland",
    description: "Charming inn surrounded by meadows.",
    image: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=900&auto=format&fit=crop&q=60",
    price: 100,
    location: "Krakow",
    country: "Poland",
  },
  {
    title: "Safari Camp in Tanzania",
    description: "Tented camp in Serengeti with game drives.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=900&auto=format&fit=crop&q=60",
    price: 350,
    location: "Serengeti",
    country: "Tanzania",
  },
  {
    title: "River Cabin in Norway",
    description: "Cabin along a river with fishing spots.",
    image: "https://images.unsplash.com/photo-1598928506311-c55ded5d4c9d?w=900&auto=format&fit=crop&q=60",
    price: 180,
    location: "Oslofjord",
    country: "Norway",
  },
  {
    title: "Studio Apartment in Seoul",
    description: "Compact studio near shopping districts.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&auto=format&fit=crop&q=60",
    price: 600,
    location: "Gangnam",
    country: "South Korea",
  },
  {
    title: "Forest Lodge in New Zealand",
    description: "Lodge surrounded by natural landscapes.",
    image: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=900&auto=format&fit=crop&q=60",
    price: 320,
    location: "Rotorua",
    country: "New Zealand",
  },
  {
    title: "Downtown Flat in Barcelona",
    description: "Apartment with easy access to Las Ramblas.",
    image: "https://images.unsplash.com/photo-1505691723518-36a1b1a4d12e?w=900&auto=format&fit=crop&q=60",
    price: 900,
    location: "Barcelona",
    country: "Spain",
  },
  {
    title: "Mountain Hut in Nepal",
    description: "Basic hut stay for trekkers in the Himalayas.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&auto=format&fit=crop&q=60",
    price: 60,
    location: "Annapurna",
    country: "Nepal",
  },
  {
    title: "Luxury Villa in Phuket",
    description: "Private villa with infinity pool and sea views.",
    image: "https://images.unsplash.com/photo-1573496529574-be85d6a60704?w=900&auto=format&fit=crop&q=60",
    price: 1100,
    location: "Phuket",
    country: "Thailand",
  },
  {
    title: "Countryside Barn in England",
    description: "Converted barn with rustic charm.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&auto=format&fit=crop&q=60",
    price: 250,
    location: "Cotswolds",
    country: "UK",
  },
  {
    title: "Coastal Villa in Portugal",
    description: "Modern villa with direct beach access.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=900&auto=format&fit=crop&q=60",
    price: 700,
    location: "Algarve",
    country: "Portugal",
  },
  {
    title: "City Apartment in Chicago",
    description: "High-rise apartment with Lake Michigan views.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&auto=format&fit=crop&q=60",
    price: 1800,
    location: "Chicago",
    country: "USA",
  },
  {
    title: "Island Hut in Philippines",
    description: "Simple bamboo hut on a remote island.",
    image: "https://images.unsplash.com/photo-1505691723518-36a1b1a4d12e?w=900&auto=format&fit=crop&q=60",
    price: 80,
    location: "Palawan",
    country: "Philippines",
  },
  {
    title: "Snow Lodge in Canada",
    description: "Ski lodge surrounded by snowy mountains.",
    image: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=900&auto=format&fit=crop&q=60",
    price: 280,
    location: "Whistler",
    country: "Canada",
  }
];

module.exports =  sampleListings ;
